--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io414image_310.jpg"

-- Special
background="#131514"
foreground="#e3e2e0"
cursor="#e3e2e0"

-- Colors
color0="#131514"
color1="#758675"
color2="#A08E70"
color3="#C89F73"
color4="#798D86"
color5="#A3A698"
color6="#CFBFA8"
color7="#e3e2e0"
color8="#9e9e9c"
color9="#758675"
color10="#A08E70"
color11="#C89F73"
color12="#798D86"
color13="#A3A698"
color14="#CFBFA8"
color15="#e3e2e0"
