# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io414image_310.jpg'

# Special
background='#131514'
foreground='#e3e2e0'
cursor='#e3e2e0'

# Colors
color0='#131514'
color1='#758675'
color2='#A08E70'
color3='#C89F73'
color4='#798D86'
color5='#A3A698'
color6='#CFBFA8'
color7='#e3e2e0'
color8='#9e9e9c'
color9='#758675'
color10='#A08E70'
color11='#C89F73'
color12='#798D86'
color13='#A3A698'
color14='#CFBFA8'
color15='#e3e2e0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
