--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io490image_45.jpg"

-- Special
background="#081612"
foreground="#dfdfe0"
cursor="#dfdfe0"

-- Colors
color0="#081612"
color1="#1C8D27"
color2="#509738"
color3="#6A955A"
color4="#8E9B6D"
color5="#A4A8A0"
color6="#BEC0BD"
color7="#dfdfe0"
color8="#9c9c9c"
color9="#1C8D27"
color10="#509738"
color11="#6A955A"
color12="#8E9B6D"
color13="#A4A8A0"
color14="#BEC0BD"
color15="#dfdfe0"
