# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io490image_45.jpg'

# Special
background='#081612'
foreground='#dfdfe0'
cursor='#dfdfe0'

# Colors
color0='#081612'
color1='#1C8D27'
color2='#509738'
color3='#6A955A'
color4='#8E9B6D'
color5='#A4A8A0'
color6='#BEC0BD'
color7='#dfdfe0'
color8='#9c9c9c'
color9='#1C8D27'
color10='#509738'
color11='#6A955A'
color12='#8E9B6D'
color13='#A4A8A0'
color14='#BEC0BD'
color15='#dfdfe0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
