--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/image_3.jpg"

-- Special
background="#10100c"
foreground="#c5c1a3"
cursor="#c5c1a3"

-- Colors
color0="#10100c"
color1="#61602C"
color2="#6C6E32"
color3="#716B48"
color4="#8A7649"
color5="#7A8535"
color6="#9B9945"
color7="#c5c1a3"
color8="#898772"
color9="#61602C"
color10="#6C6E32"
color11="#716B48"
color12="#8A7649"
color13="#7A8535"
color14="#9B9945"
color15="#c5c1a3"
