# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/image_3.jpg'

# Special
background='#10100c'
foreground='#c5c1a3'
cursor='#c5c1a3'

# Colors
color0='#10100c'
color1='#61602C'
color2='#6C6E32'
color3='#716B48'
color4='#8A7649'
color5='#7A8535'
color6='#9B9945'
color7='#c5c1a3'
color8='#898772'
color9='#61602C'
color10='#6C6E32'
color11='#716B48'
color12='#8A7649'
color13='#7A8535'
color14='#9B9945'
color15='#c5c1a3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
