--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io219image_157.jpg"

-- Special
background="#111a1f"
foreground="#c0c7ca"
cursor="#c0c7ca"

-- Colors
color0="#111a1f"
color1="#8D7856"
color2="#798362"
color3="#9B9257"
color4="#63768A"
color5="#738C9C"
color6="#6998B3"
color7="#c0c7ca"
color8="#868b8d"
color9="#8D7856"
color10="#798362"
color11="#9B9257"
color12="#63768A"
color13="#738C9C"
color14="#6998B3"
color15="#c0c7ca"
