--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/image_177.jpg"

-- Special
background="#100f0b"
foreground="#bfcfde"
cursor="#bfcfde"

-- Colors
color0="#100f0b"
color1="#AC9569"
color2="#737C81"
color3="#789BC3"
color4="#A2A5A2"
color5="#BBC1BE"
color6="#E3D1AF"
color7="#bfcfde"
color8="#85909b"
color9="#AC9569"
color10="#737C81"
color11="#789BC3"
color12="#A2A5A2"
color13="#BBC1BE"
color14="#E3D1AF"
color15="#bfcfde"
