--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io640image_244.jpg"

-- Special
background="#030616"
foreground="#a5c5df"
cursor="#a5c5df"

-- Colors
color0="#030616"
color1="#0E378A"
color2="#0C3DA2"
color3="#15488F"
color4="#1F5DA9"
color5="#2E73BF"
color6="#4689C1"
color7="#a5c5df"
color8="#73899c"
color9="#0E378A"
color10="#0C3DA2"
color11="#15488F"
color12="#1F5DA9"
color13="#2E73BF"
color14="#4689C1"
color15="#a5c5df"
