# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io640image_244.jpg'

# Special
background='#030616'
foreground='#a5c5df'
cursor='#a5c5df'

# Colors
color0='#030616'
color1='#0E378A'
color2='#0C3DA2'
color3='#15488F'
color4='#1F5DA9'
color5='#2E73BF'
color6='#4689C1'
color7='#a5c5df'
color8='#73899c'
color9='#0E378A'
color10='#0C3DA2'
color11='#15488F'
color12='#1F5DA9'
color13='#2E73BF'
color14='#4689C1'
color15='#a5c5df'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
