# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io884image_26.jpg'

# Special
background='#101811'
foreground='#b3d7d4'
cursor='#b3d7d4'

# Colors
color0='#101811'
color1='#718964'
color2='#037C83'
color3='#4F7C83'
color4='#038E91'
color5='#25A09F'
color6='#5EA9A5'
color7='#b3d7d4'
color8='#7d9694'
color9='#718964'
color10='#037C83'
color11='#4F7C83'
color12='#038E91'
color13='#25A09F'
color14='#5EA9A5'
color15='#b3d7d4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
