--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io884image_26.jpg"

-- Special
background="#101811"
foreground="#b3d7d4"
cursor="#b3d7d4"

-- Colors
color0="#101811"
color1="#718964"
color2="#037C83"
color3="#4F7C83"
color4="#038E91"
color5="#25A09F"
color6="#5EA9A5"
color7="#b3d7d4"
color8="#7d9694"
color9="#718964"
color10="#037C83"
color11="#4F7C83"
color12="#038E91"
color13="#25A09F"
color14="#5EA9A5"
color15="#b3d7d4"
