# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io219image_157.jpg'

# Special
background='#111a1f'
foreground='#c0c7ca'
cursor='#c0c7ca'

# Colors
color0='#111a1f'
color1='#8D7856'
color2='#798362'
color3='#9B9257'
color4='#63768A'
color5='#738C9C'
color6='#6998B3'
color7='#c0c7ca'
color8='#868b8d'
color9='#8D7856'
color10='#798362'
color11='#9B9257'
color12='#63768A'
color13='#738C9C'
color14='#6998B3'
color15='#c0c7ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
