--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/batman-sign-logo-dark-4k.jpg"

-- Special
background="#000000"
foreground="#7ebdcf"
cursor="#7ebdcf"

-- Colors
color0="#000000"
color1="#074E65"
color2="#054A74"
color3="#033886"
color4="#05538A"
color5="#096A94"
color6="#0A74A6"
color7="#7ebdcf"
color8="#588490"
color9="#074E65"
color10="#054A74"
color11="#033886"
color12="#05538A"
color13="#096A94"
color14="#0A74A6"
color15="#7ebdcf"
