# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/batman-sign-logo-dark-4k.jpg'

# Special
background='#000000'
foreground='#7ebdcf'
cursor='#7ebdcf'

# Colors
color0='#000000'
color1='#074E65'
color2='#054A74'
color3='#033886'
color4='#05538A'
color5='#096A94'
color6='#0A74A6'
color7='#7ebdcf'
color8='#588490'
color9='#074E65'
color10='#054A74'
color11='#033886'
color12='#05538A'
color13='#096A94'
color14='#0A74A6'
color15='#7ebdcf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
