# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io200image_56.jpg'

# Special
background='#190c0d'
foreground='#ecd4d3'
cursor='#ecd4d3'

# Colors
color0='#190c0d'
color1='#DB745B'
color2='#FBAC3B'
color3='#F08D6B'
color4='#744989'
color5='#A8658D'
color6='#EDA29D'
color7='#ecd4d3'
color8='#a59493'
color9='#DB745B'
color10='#FBAC3B'
color11='#F08D6B'
color12='#744989'
color13='#A8658D'
color14='#EDA29D'
color15='#ecd4d3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
