--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cowboy-bebop-wallpaper-17.jpg"

-- Special
background="#0C0A07"
foreground="#e0c8a7"
cursor="#e0c8a7"

-- Colors
color0="#0C0A07"
color1="#976131"
color2="#936D38"
color3="#A27A42"
color4="#BB863E"
color5="#B28A4B"
color6="#A99061"
color7="#e0c8a7"
color8="#9c8c74"
color9="#976131"
color10="#936D38"
color11="#A27A42"
color12="#BB863E"
color13="#B28A4B"
color14="#A99061"
color15="#e0c8a7"
