# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cowboy-bebop-wallpaper-17.jpg'

# Special
background='#0C0A07'
foreground='#e0c8a7'
cursor='#e0c8a7'

# Colors
color0='#0C0A07'
color1='#976131'
color2='#936D38'
color3='#A27A42'
color4='#BB863E'
color5='#B28A4B'
color6='#A99061'
color7='#e0c8a7'
color8='#9c8c74'
color9='#976131'
color10='#936D38'
color11='#A27A42'
color12='#BB863E'
color13='#B28A4B'
color14='#A99061'
color15='#e0c8a7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
