# Shell variables
# Generated by 'wal'
wallpaper='/Users/ryuta69/Downloads/cdn.leoh.io470image_109.jpg'

# Special
background='#191e22'
foreground='#e3e0dc'
cursor='#e3e0dc'

# Colors
color0='#191e22'
color1='#3B5D85'
color2='#637291'
color3='#3F8180'
color4='#708D94'
color5='#9DA4A6'
color6='#BDBEBD'
color7='#e3e0dc'
color8='#9e9c9a'
color9='#3B5D85'
color10='#637291'
color11='#3F8180'
color12='#708D94'
color13='#9DA4A6'
color14='#BDBEBD'
color15='#e3e0dc'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
