--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io470image_109.jpg"

-- Special
background="#191e22"
foreground="#e3e0dc"
cursor="#e3e0dc"

-- Colors
color0="#191e22"
color1="#3B5D85"
color2="#637291"
color3="#3F8180"
color4="#708D94"
color5="#9DA4A6"
color6="#BDBEBD"
color7="#e3e0dc"
color8="#9e9c9a"
color9="#3B5D85"
color10="#637291"
color11="#3F8180"
color12="#708D94"
color13="#9DA4A6"
color14="#BDBEBD"
color15="#e3e0dc"
