--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/Users/ryuta69/Downloads/cdn.leoh.io200image_56.jpg"

-- Special
background="#190c0d"
foreground="#ecd4d3"
cursor="#ecd4d3"

-- Colors
color0="#190c0d"
color1="#DB745B"
color2="#FBAC3B"
color3="#F08D6B"
color4="#744989"
color5="#A8658D"
color6="#EDA29D"
color7="#ecd4d3"
color8="#a59493"
color9="#DB745B"
color10="#FBAC3B"
color11="#F08D6B"
color12="#744989"
color13="#A8658D"
color14="#EDA29D"
color15="#ecd4d3"
